version: '3.7'

services: 
  db: 
    container_name: nest_db
    image: postgres:13
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    volumes:
      - nest_db_data:/var/lib/postgresql/data

volumes:
  nest_db_data:
    name: nest_db_data