export const CLASS_TOKENS = {
    USER: Symbol('USER_REPOSITORY'),
    USER_SHOWING_SERVICE: Symbol('USER_SHOWING_SERVICE'),
    USER_SESSION: Symbol('USER_SESSION_REPOSITORY'),
    POST: Symbol('POST_REPOSITORY'),
    COMMENT: Symbol('COMMENT_REPOSITORY'),
    DRAFT: Symbol('DRAFT_REPOSITORY'),
    REGISTER_SERVICE: Symbol('REGISTER_SERVICE'),
    HASHING_SERVICE: Symbol('HASHING_SERVICE'),
    LOGIN_SERVICE: Symbol('LOGIN_SERVICE'),
    AUTH_SERVICE: Symbol('AUTH_SERVICE'),
    JWT_SERVICE: Symbol('JWT_SERVICE'),
} as const;
